poc/Docker/Docker/Controllers/HomeController.cs
using Docker.DAL;
using Docker.Models;
using Docker.Services;
using Microsoft.AspNetCore.Mvc;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;

namespace Docker.Controllers
{
    public class HomeController : Controller
    {
        private ITaskBuilderService _taskBuilder;
        private DockerContext _dbContext;
        private ILoaderService _loader;

        public HomeController(ITaskBuilderService taskBuilder, DockerContext dbContext, ILoaderService loader)
        {
            _taskBuilder = taskBuilder;
            _dbContext = dbContext;
            _loader = loader;
        }

        public IActionResult Index()
        {
            //Ship ship = _dbContext.Ships.Where(s => s.Name.ToUpper() == "MAR32").First();
            //Dock dock = _dbContext.Docks.Where(d => d.Name.ToUpper() == "DOCK23").First();
            Ship ship = DBInitializer.ship;
            Dock dock = DBInitializer.dock;

            var tasks = _taskBuilder.GenerateTasksForShip(ship, dock);
            ViewData["tasks"] = tasks;
            ViewData["current"] = tasks[0];
            ViewData["refresh"] = false;

            
            ViewData["ship"] = DBFaker.ships[0]; 
            ViewData["dock"] = DBFaker.docks[0];

            return View();
        }

        public IActionResult ProcessTask()
        {
            Ship ship = DBFaker.ships[0];
            Dock dock = DBFaker.docks[0];

            var tasks = _loader.ProcessTasks(dock.Name);

            //var tasks = _dbContext.Tasks.ToList

            //Models.Task crntTask = _dbContext.Tasks.Where(t => t.Status == TaskStatus.INPROGRESS).First(); // get the first task that is in progrDeess, for later - select all and adjust the index to have a list of executed tasks in progress
            Models.Task crntTask = null;
            foreach (Models.Task t in tasks)
            {
                if (t.Status == TaskStatus.INPROGRESS)
                {
                    crntTask = t;
                    break;
                }
            }
            if (crntTask == null)
            {
                crntTask = DBFaker.GetNextReadyTask();
            }

            //crntTask.Payload = _dbContext.Containers.Where(c => c.TaskID == crntTask.ID).Single();
            ViewData["current"] = crntTask;
            if(crntTask == null)
            {
                ViewData["refresh"] = false;
            }
            else
            {
                ViewData["refresh"] = true;
            }
            
            ViewData["tasks"] = tasks;
            ViewData["ship"] = ship;
            ViewData["dock"] = dock;
            return View("Index");
        }

        public IActionResult StopRefresh()
        {
            ViewData["current"] = null;
            ViewData["refresh"] = false;

            Ship ship = DBFaker.ships[0];
            ViewData["ship"] = ship;
            ViewData["dock"] = DBFaker.docks[0];

            ViewData["tasks"] = DBFaker.tasks;
            return View("Index");
        }
    }
}

poc/Docker/Docker/ViewComponents/FrontSliceViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Docker.DAL;
using Docker.Models;
using Microsoft.AspNetCore.Mvc;

namespace Docker.ViewComponents
{
    public class FrontSliceViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(int y)
        {
            ContainerCollection cc = DBInitializer.ship;
            Container[,] slice = new Container[cc.X, cc.Z];

            foreach (Container ccContainer in cc.Containers)
            {
                int tempX = ccContainer.X;
                int tempY = ccContainer.Y;
                int tempZ = ccContainer.Z;
                if (tempY == y)
                {
                    slice[tempX, tempZ] = ccContainer;
                }
            }

            return View(slice);
        }
    }
}

poc/Docker/Docker/ViewComponents/SideSliceViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Docker.DAL;
using Docker.Models;
using Microsoft.AspNetCore.Mvc;

namespace Docker.ViewComponents
{
    public class SideSliceViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(int x)
        {
            ContainerCollection cc = DBInitializer.ship;
            Container[,] slice = new Container[cc.Y, cc.Z];
            foreach (Container ccContainer in cc.Containers)
            {
                int tempX = ccContainer.X;
                int tempY = ccContainer.Y;
                int tempZ = ccContainer.Z;
                if (tempX == x)
                {
                    slice[tempY, tempZ] = ccContainer;
                }
            }

            return View(slice);
        }
    }
}

poc/Docker/Docker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@{
    List<Docker.Models.Task> tasks = (List<Docker.Models.Task>)ViewData["tasks"];
    Docker.Models.Task current = (Docker.Models.Task)ViewData["current"];
    // for the ship and dock displays
    Docker.Models.Ship mainship = (Docker.Models.Ship)ViewData["ship"];
    Docker.Models.Dock maindock = (Docker.Models.Dock)ViewData["dock"];
    //Get current tasks from loader

    //test data
    Random rn = new Random();
    Docker.Models.Ship ship;
    ship = new Docker.Models.Ship();
    ship.X = 3;
    ship.Y = 3;
    ship.Z = 3;
    ship.Containers = new List<Docker.Models.Container>();
    ship.Name = "MAR32";

    for (int i = 0; i < ship.X || i < ship.Z || i < ship.Y; i++)
    {
        ship.Containers.Add(new Docker.Models.Container()
        {
            ContainerLocation = ship,
            X = i,
            Y = i,
            Z = i,
            ID = rn.Next(0, int.MaxValue)
        });
    }
}
@{
    if ((bool)ViewData["refresh"])
    {
        <meta http-equiv="refresh" content="1;url=/Home/ProcessTask" />
    }
}
<div class="col-md-9">
    <table class="table">
        <tr>
            <td>
                <h1>Ship side:</h1>
                <div class="col-md-12">
                    <p>Depth: <span class="glyphicon glyphicon-plus"></span> 0 <span class="glyphicon glyphicon-minus"></span>
                    </p>
                </div>
                <div class="col-md-12">
                    @await Component.InvokeAsync("SideSlice", new { cc = ship, x = 0 })
                </div>
            </td>
            <td>
                <h1>Ship front:</h1>
                <div class="col-md-12 text-cente">
                    <p>Depth: <span class="glyphicon glyphicon-plus"></span> 0 <span class="glyphicon glyphicon-minus"></span></p>
                </div>
                <div class="col-md-12">
                    @await Component.InvokeAsync("FrontSlice", new { cc = ship, y = 0 })
                </div>
            </td>
            <td>
                Dock Side
            </td>
            <td>
                Dock Front
            </td>
        </tr>
        <tr>
            <td colspan="4" class="text-center">Ship + Dock picture</td>
        </tr>
    </table>
    <div class="col-md-4 text-center">
        <h4>Ship</h4>
        @if (mainship != null)
        {
            <h4>@mainship.Name</h4>
            <table class="table table-hover table-bordered table-compact">
                <thead>
                    <tr class="">
                        <th>Container</th>
                        <th>Location</th>
                        <th>Serial Number</th>
                    </tr>
                </thead>
                <tbody class="text-center panel-body">
                    @foreach (Docker.Models.Container c in mainship.Containers)
                    {
                        <tr>
                            <td><h6>@c.ID</h6></td>
                            <td><h6>@c.X ; @c.Y; @c.Z</h6></td>
                            <td><h6>@c.SerialNumber.Substring(0, 10)...</h6></td>
                        </tr>

                    }
                </tbody>
                </table>
        }
        else
        {
            <div>
                <h6>No ships are available...</h6>
            </div>

        }
</div>
    <div class="col-md-4  text-center">
        <h4>Dock</h4>
        @if (maindock != null)
        {
            <h4>@maindock.Name</h4>
            <table class="table table-hover table-bordered table-compact">
                <thead>
                    <tr class="">
                        <th>Container</th>
                        <th>Location</th>
                        <th>Serial Number</th>
                    </tr>
                </thead>
                <tbody class="text-center panel-body">
                    @foreach (Docker.Models.Container c in maindock.Containers)
                    {
                        <tr>
                            <td><h6>@c.ID</h6></td>
                            <td><h6>@c.X ; @c.Y; @c.Z</h6></td>
                            <td><h6>@c.SerialNumber.Substring(0,10)...</h6></td>
                        </tr>

                    }
                </tbody>
            </table>
        }
        else
        {
            <div>
                <h6>No ships are available...</h6>
            </div>

        }
    </div>
</div>
<div class="col-md-3">
    <div class="table-responsive">
        <div class="panel panel-success">
            <div class="panel-heading text-center"><h4>Current Tasks</h4></div>
            @*Loop trough current tasks*@
            @*@Html.ActionLink("Do task", "ProcessTask", "Home")*@
            <div class="text-center">
                <a href="@Url.Action("ProcessTask", "Home")" class="btn btn-secondary">
                    Do Task
                    <span class="glyphicon glyphicon glyphicon-play" aria-hidden="true"></span>
                </a>
                @* @Html.ActionLink("Complete all", "StopRefresh", "Home")*@
                <a href="@Url.Action("StopRefresh", "Home")" class="btn btn-secondary">
                    Stop Refreshing
                    <span class="glyphicon glyphicon-pause" aria-hidden="true"></span>
                </a>
            </div>            
            @if (current != null)
            {
                    <div class="panel-body">
                        <div class="col-md-8">
                            <div class="col-md-6">
                                <div class="row"><span class="glyphicon glyphicon-barcode" aria-hidden="true"></span> Container id</div>
                                <div class="row"><span class="glyphicon glyphicon-screenshot" aria-hidden="true"></span>Location</div>
                                <div class="row"><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>Destination</div>
                            </div>
                            <div class="col-md-6">
                                <div class="row">@current.Payload.ID</div>
                                <div class="row">@current.Payload.ContainerLocation.Name @current.Payload.X:@current.Payload.Y:@current.Payload.Z</div>
                                <div class="row">@current.Destination.Name</div>
                            </div>
                        </div>
                        <div class="col-md-4 text-left">
                            <h3>@current.RequiredTime.ToString()</h3>
                        </div>
                    </div>
                }
            </div>
        <table class="table table-hover table-bordered table-compact">
            <thead>
                <tr class="">
                    <th>Container</th>
                    <th>Location</th>
                    <th>Destination</th>
                    <th>ET</th>
                    <th>Info</th>
                </tr>
            </thead>
            <tbody class="text-center panel-body">
                @if(tasks == null){
                <tr>
                    <td colspan="5">There are no tasks left or the process was stopped</td>
                </tr>
                }else{

                for(int i = 0; i < tasks.Count; i++)
                {
                    Docker.Models.Task task = tasks[i];
<<<<<<< HEAD:Docker/Docker/Views/Home/Index.cshtml
                    
                    <tr class="@(@task.RequiredTime.TotalMinutes <= 0 ? "bg-success" : "")">
=======

                    <tr class="@(@task.Status == Docker.Models.TaskStatus.FINISHED ? "bg-success" : @task.Status == Docker.Models.TaskStatus.INPROGRESS ? "bg-warning" : "")">
>>>>>>> a608ea5fb7fd3f5e3f8b7a54e69d28ae39af88be:poc/Docker/Docker/Views/Home/Index.cshtml
                        <td>@task.Payload.ID</td>
                        <td>
                            @task.Payload.ContainerLocation.Name
                           <br />@task.Payload.X : @task.Payload.Y : @task.Payload.Z
                        </td>
                        <td>@task.Destination.Name</td>
                        <td>@task.RequiredTime.TotalMinutes minutes</td>
                        <td>
                            <button type="button" class="btn-sm btn-info" data-toggle="modal" data-target="#taskInfo-@task.Payload.ID">
                                Info
                            </button>
                        </td>
                    </tr>

                    <div class="modal fade" id="taskInfo-@task.Payload.ID" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title text-center" id="exampleModalLabel">Task details</h3>
                                </div>
                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-md-7">
                                            <p><b>Container: @task.Payload.ID</b></p>
                                            <p><b>Location: @task.Payload.ContainerLocation.Name - @task.Payload.X : @task.Payload.Y : @task.Payload.Z</b></p>
                                            <p><b>Destination: @task.Destination.Name</b></p>
                                            <p><b>Time created: @task.TimeCreated.ToString()</b></p>
                                            <p><b>Time modified: @task.TimeModified.ToString()</b></p>
                                            <p><b>ETC: @task.RequiredTime.TotalMinutes minutes</b></p>
                                        </div>
                                        <div class="col-md-5">
                                            <img src="images/container.png" class="img-responsive" alt="Container blue">
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <button type="button" class="btn btn-primary btn-sm btn-block" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                }
            </tbody>
        </table>
    </div>
</div>